version: '3'
services:
    db:
        container_name: short_it_dev_db
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=urldb
            - POSTGRES_USER=urluser
            - POSTGRES_PASSWORD=password
        volumes:
            - 'dbdata:/var/lib/postgresql/data'
            - './db:/docker-entrypoint-initdb.d/:ro'
volumes:
    dbdata:
